In [ ]:
import numpy as np

: 

# 1. Introduction

In [1]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

NameError: name 'np' is not defined

# 2. The NumPy ndarray: A Multidimensional Array Object

## 2.1. Creating arrays

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

data * 10

NameError: name 'np' is not defined

In [4]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

---

In [5]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

---

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2.ndim

2

In [10]:
arr1 = np.array([6, 7.5, 8, 0, 1])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

---

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.empty((2, 3, 2))

array([[[9.87862300e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.06099790e-312, 4.47032019e-038]],

       [[4.96926329e-091, 1.77102525e-051],
        [4.29112840e-038, 3.95235315e+179],
        [3.99910963e+252, 1.10656735e-046]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
a = [1, 2]
type(np.asarray(a))

numpy.ndarray

In [19]:
x = np.arange(6)
np.ones_like(x)

array([1, 1, 1, 1, 1, 1])

In [20]:
x = np.arange(6)
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0])

In [21]:
x = np.arange(6)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(3)

NameError: name 'numpy' is not defined

In [24]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

---

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr1.dtype

dtype('float64')

In [26]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

In [27]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

## 2.2. Arithmetics with NumPy

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr * arr)   # Mutiplication
print(arr / arr)   # Division
print(arr + arr)   # Addition
print(arr - arr)   # Subtraction

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
m

[[ 3.  6.  9.]
 [12. 15. 18.]]
[[3.   1.5  1.  ]
 [0.75 0.6  0.5 ]]
[[4. 5. 6.]
 [7. 8. 9.]]
[[-2. -1.  0.]
 [ 1.  2.  3.]]


In [30]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

---

In [31]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5]

5

In [33]:
arr[5:8]

array([5, 6, 7])

In [34]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr = np.arange(10)
arr_slice = arr[5:8]

arr_slice

array([5, 6, 7])

In [36]:
arr_slice[:] = 100

arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

----

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[1]

array([4, 5, 6])

In [38]:
print(arr2d[0][2])

print(arr2d[0, 2])

3
3


In [39]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[1]

array([4, 5, 6])

---

In [40]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 2.3. Basic Indexing and Slicing

In [42]:
arr = np.arange(10)

arr[1:6]

array([1, 2, 3, 4, 5])

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

## 2.4. Boolean Indexing

In [2]:
names = np.array(["Bob", "Joe", "Will", "Bob",
                  "Will", "Joe", "Joe"])

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0],
                 [1, 2], [-12, -4], [3, 4]])

NameError: name 'np' is not defined

In [1]:
names == "Bob"

NameError: name 'names' is not defined

In [47]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [48]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [49]:
data[names == "Bob", 1]

array([7, 0])

In [50]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [51]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [52]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [53]:
cond = names == "Bob"

data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [54]:
mask = (names == "Bob") | (names == "Will")

mask

array([ True, False,  True,  True,  True, False, False])

In [55]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [56]:
data[data < 0] = 0

data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [57]:
data[names != "Joe"] = 7

data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## 2.5. Fancy Indexing

In [58]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [60]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [61]:
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [63]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 2.6. Transposing Arrays and Swapping Axes

In [64]:
arr = np.arange(15).reshape((3, 5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [66]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

try:
  np.dot(arr, arr)
except:
  print('---------------------------------------------------------------------------')
  print('ValueError                                Traceback (most recent call last)')
  print('.\\Numpy_for_Beginners.ipynb Cell 81 line 3')
  print('      1 arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])')
  print('----> 3 np.dot(arr, arr)')
  print('\nValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
.\Numpy_for_Beginners.ipynb Cell 81 line 3
      1 arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
----> 3 np.dot(arr, arr)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)


In [67]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [68]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [69]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

# 3. Pseudorandom Number Generation

In [70]:
samples = np.random.standard_normal(size=(4, 4))

samples

array([[ 0.5514243 ,  1.65930884,  0.71477128, -0.56424618],
       [ 0.19154429,  0.33274705, -0.68386859,  0.55921142],
       [-0.56692653, -0.29609306,  0.45572122,  0.62668531],
       [-0.45086496,  2.34724647,  1.62531117,  0.91393796]])

In [71]:
from random import normalvariate

N = 1_000_000

%timeit samples = [normalvariate(0, 1) for _ in range(N)]

%timeit np.random.standard_normal(N)

465 ms ± 4.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
16.3 ms ± 48.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
rng = np.random.default_rng(seed=12345)

data = rng.standard_normal((2, 3))

type(rng)

numpy.random._generator.Generator

# 4. Universal Functions: Fast Element-Wise Array Functions

In [73]:
arr = np.arange(10)

rng = np.random.default_rng(seed=12345)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

---

In [76]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [77]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [78]:
np.add(x, y)

array([-1.06276692, -0.6891346 ,  1.47674792,  0.70932367, -0.83473049,
        0.16131362, -1.83474588,  0.58820328])

In [79]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

---

In [80]:
arr = rng.standard_normal(7) * 5

arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [81]:
remainder, whole_part = np.modf(arr)

remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [82]:
whole_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

---

In [83]:
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [84]:
out = np.zeros_like(arr)

np.add(arr, 1)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [85]:
np.add(arr, 1, out=out)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [86]:
out

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

# 5. Array-Oriented Programming with Arrays

In [87]:
points = np.arange(-5, 5, 0.01)

xs, ys = np.meshgrid(points, points)

xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [88]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [89]:
z = np.sqrt(xs ** 2 + ys ** 2)

z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

## 5.1. Expressing Conditional Logic as Array Operations

In [90]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [91]:
result = np.where(cond, xarr, yarr)

result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [92]:
arr = rng.standard_normal((4, 4))

arr

array([[-1.62158273, -0.15818926,  0.44948393, -1.34360107],
       [-0.08168759,  1.72473993,  2.61815943,  0.77736134],
       [ 0.8286332 , -0.95898831, -1.20938829, -1.41229201],
       [ 0.54154683,  0.7519394 , -0.65876032, -1.22867499]])

In [93]:
arr > 0

array([[False, False,  True, False],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False, False]])

In [94]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2, -2],
       [-2,  2,  2,  2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

In [95]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-1.62158273, -0.15818926,  2.        , -1.34360107],
       [-0.08168759,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.95898831, -1.20938829, -1.41229201],
       [ 2.        ,  2.        , -0.65876032, -1.22867499]])

## 5.2. Mathematical and Statistical Methods

In [96]:
arr = rng.standard_normal((5, 4))

arr

array([[ 0.25755777,  0.31290292, -0.13081169,  1.26998312],
       [-0.09296246, -0.06615089, -1.10821447,  0.13595685],
       [ 1.34707776,  0.06114402,  0.0709146 ,  0.43365454],
       [ 0.27748366,  0.53025239,  0.53672097,  0.61835001],
       [-0.79501746,  0.30003095, -1.60270159,  0.26679883]])

In [97]:
print(arr.mean())
print(np.mean(arr))

0.13114849172877924
0.13114849172877924


In [98]:
arr.sum()

2.622969834575585

In [99]:
arr.std()

0.674973871220971

---

In [100]:
arr.mean(axis=0)

array([ 0.19882786,  0.22763588, -0.44681844,  0.54494867])

In [101]:
arr.mean(axis=1)

array([ 0.42740803, -0.28284274,  0.47819773,  0.49070176, -0.45772232])

In [102]:
arr.sum(axis=0)

array([ 0.99413928,  1.13817938, -2.23409218,  2.72474335])

In [103]:
arr.sum(axis=1)

array([ 1.70963212, -1.13137096,  1.91279092,  1.96280703, -1.83088927])

---

In [104]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [105]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [107]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

## 5.3. Methods for Boolean Arrays

In [108]:
arr = rng.standard_normal(100)

print((arr > 0).sum()) # Number of positive values
print((arr <= 0).sum()) # Number of non-positive values

49
51


In [109]:
bools = np.array([False, False, True, False])

print(bools.any())
print(bools.all())

True
False


## 5.4. Sorting

In [110]:
arr = rng.standard_normal(6)

arr

array([-1.02755181, -1.2292893 , -0.88335847, -0.07089346,  0.37405335,
       -0.02459374])

In [111]:
arr.sort()

arr

array([-1.2292893 , -1.02755181, -0.88335847, -0.07089346, -0.02459374,
        0.37405335])

---

In [112]:
arr = rng.standard_normal((5, 3))

arr

array([[ 0.07726066, -0.68391322, -0.72083767],
       [ 1.12062282, -0.05481416, -0.08241372],
       [ 0.9359865 ,  1.23853712,  1.27279553],
       [ 0.40589222, -0.05032522,  0.28931754],
       [ 0.17930568,  1.39748056,  0.29204679]])

In [113]:
arr.sort(axis=0)

arr

array([[ 0.07726066, -0.68391322, -0.72083767],
       [ 0.17930568, -0.05481416, -0.08241372],
       [ 0.40589222, -0.05032522,  0.28931754],
       [ 0.9359865 ,  1.23853712,  0.29204679],
       [ 1.12062282,  1.39748056,  1.27279553]])

In [114]:
arr.sort(axis=1)

arr

array([[-0.72083767, -0.68391322,  0.07726066],
       [-0.08241372, -0.05481416,  0.17930568],
       [-0.05032522,  0.28931754,  0.40589222],
       [ 0.29204679,  0.9359865 ,  1.23853712],
       [ 1.12062282,  1.27279553,  1.39748056]])

---

In [115]:
arr2 = np.array([5, -10, 7, 1, 0, -3])

sorted_arr2 = np.sort(arr2)

sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

## 5.5. Unique and Other Set Logic

In [116]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [117]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

np.unique(ints)

array([1, 2, 3, 4])

---

In [118]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

# 6. File Input and Output with Arrays

In [119]:
arr = np.arange(10)

np.save("some_array", arr)

np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.savez("array_archive.npz", a=arr, b=arr)

In [121]:
arch = np.load("array_archive.npz")

arch

NpzFile 'array_archive.npz' with keys: a, b

In [122]:
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

# 7. Linear Algebra

In [124]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [125]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [126]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [127]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

---

In [128]:
x @ np.ones(3)

array([ 6., 15.])

---

In [129]:
from numpy.linalg import inv, qr

X = rng.standard_normal((5, 5))

mat = X.T @ X

inv(mat)

array([[0.20152551, 0.27247672, 0.22084728, 0.32572635, 0.4383584 ],
       [0.27247672, 1.73833166, 1.25221553, 1.48306376, 1.88258355],
       [0.22084728, 1.25221553, 1.09259636, 1.18986272, 1.44889734],
       [0.32572635, 1.48306376, 1.18986272, 1.56549544, 1.86755999],
       [0.4383584 , 1.88258355, 1.44889734, 1.86755999, 4.13669025]])

In [130]:
mat @ inv(mat)

array([[ 1.00000000e+00,  3.82293825e-16,  1.41046879e-16,
         9.32989876e-16,  5.27781061e-16],
       [ 1.39447413e-16,  1.00000000e+00,  3.28041928e-16,
         1.09857636e-15,  5.51790533e-16],
       [ 2.21049345e-16, -1.66126020e-16,  1.00000000e+00,
        -1.55865271e-16,  8.01910749e-16],
       [-5.36321508e-17,  3.45341343e-16,  4.13757420e-16,
         1.00000000e+00,  8.08204083e-16],
       [-3.38780277e-17, -9.57691611e-18, -2.57315737e-17,
        -2.14577146e-16,  1.00000000e+00]])